# This is a basic workflow to help you get started with Actions

name: Update Language Source

# Controls when the action will run. 
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Update Projects Source Json
        run: |
          wget https://raw.githubusercontent.com/foundryvtt/pf2e/master/static/lang/en.json -O ./.github/en.json
          wget https://raw.githubusercontent.com/foundryvtt/pf2e/master/static/lang/re-en.json -O ./.github/re-en.json
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "['.github/en.json', '.github/re-en.json']"
          branch: main
